### ISSUE TITLE
force_password_reset fails when building tar image type

### ISSUE THREAD

**Issue by andremarianiello** [osbuild/images#724]
```
Stage: org.osbuild.users
Output:
chroot: failed to run command ‘passwd’: No such file or directory
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.users", line 145, in <module>
    r = main(args["tree"], args["options"])
  File "/run/osbuild/bin/org.osbuild.users", line 130, in main
    subprocess.run(["chroot", tree, "passwd", "--expire", name], check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['chroot', '/run/osbuild/tree', 'passwd', '--expire', 'foouser']' returned non-zero exit status 127.
```
This doesn't happen with qcow2, ova, image-installer, etc.

**Comment by achilleas-k** [comment]
Opened #741

**Comment by andremarianiello** [comment]
Hello! I am still having this issue. I think it is because the `passwd` binary is not provided by `shadow-utils` or `pam`, but by the `passwd` package. I will make a PR with my fix

**Comment by achilleas-k** [comment]
> Hello! I am still having this issue. I think it is because the `passwd` binary is not provided by `shadow-utils` or `pam`, but by the `passwd` package. I will make a PR with my fix

You're right.  That was an oversight on my part.  Thanks!
